apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mongo
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
