apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert --provider=OpenShift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    io.kompose.service: web
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g
          'daemon off;'
        env:
        - name: FLASK_SERVER_ADDR
          value: backend:9091
        image: ' '
        name: web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - web
      from:
        kind: ImageStreamTag
        name: web:latest
    type: ImageChange
status: {}
